// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJP9q_W6WNCUnpLfQXy4aiIBWlSQiqWA',
    appId: '1:807503265620:web:72e41a4fdf92d8766912c1',
    messagingSenderId: '807503265620',
    projectId: 'club-sportive',
    authDomain: 'club-sportive.firebaseapp.com',
    storageBucket: 'club-sportive.appspot.com',
    measurementId: 'G-PQ0XFE0C86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClwanXJ8zcs8vXSLP2eUJSP5YwgY7YUB0',
    appId: '1:807503265620:android:219b77ecc5d6627a6912c1',
    messagingSenderId: '807503265620',
    projectId: 'club-sportive',
    storageBucket: 'club-sportive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_5Zfz3nu_ptZSwHQtSvtuCt6T34zq-bU',
    appId: '1:807503265620:ios:f750e130ed89c51b6912c1',
    messagingSenderId: '807503265620',
    projectId: 'club-sportive',
    storageBucket: 'club-sportive.appspot.com',
    iosClientId:
        '807503265620-o8q2to22a9m2sjftk5ff4c6gotbvp3n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_5Zfz3nu_ptZSwHQtSvtuCt6T34zq-bU',
    appId: '1:807503265620:ios:163efcae99751c826912c1',
    messagingSenderId: '807503265620',
    projectId: 'club-sportive',
    storageBucket: 'club-sportive.appspot.com',
    iosClientId:
        '807503265620-5r107kl841cdbs7g09m41mqq6jif04bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
